export const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    price: 999.99,
    category: "phones",
    brand: "Apple",
    rating: 5,
    image: "/iphone-15-pro.png",
    description: "Latest iPhone with A17 Pro chip, stunning camera system, and titanium design",
    specs: ["6.1 inch display", "512GB storage", "5G enabled"],
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    price: 899.99,
    category: "phones",
    brand: "Samsung",
    rating: 4.8,
    image: "/samsung-galaxy-s24-phone.jpg",
    description: "Powerful Android phone with stunning AMOLED display and advanced AI features",
    specs: ["6.2 inch display", "256GB storage", "5G enabled"],
  },
  {
    id: 3,
    name: "MacBook Pro 16",
    price: 2499.99,
    category: "laptops",
    brand: "Apple",
    rating: 5,
    image: "/macbook-pro-16-laptop.jpg",
    description: "Professional laptop with M3 Max chip, perfect for creative work",
    specs: ["16GB RAM", "512GB SSD", "16 inch Liquid Retina display"],
  },
  {
    id: 4,
    name: "Dell XPS 15",
    price: 1799.99,
    category: "laptops",
    brand: "Dell",
    rating: 4.7,
    image: "/dell-xps-15-laptop.jpg",
    description: "Ultra-thin laptop with Intel processor and RTX graphics",
    specs: ["16GB RAM", "512GB SSD", "15.6 inch display"],
  },
  {
    id: 5,
    name: "Sony WH-1000XM5 Headphones",
    price: 399.99,
    category: "headphones",
    brand: "Sony",
    rating: 4.9,
    image: "/sony-wh-1000xm5-wireless-headphones.jpg",
    description: "Premium noise-cancelling wireless headphones with exceptional sound quality",
    specs: ["40 hour battery", "Active noise cancellation", "Bluetooth 5.3"],
  },
  {
    id: 6,
    name: "Apple AirPods Pro",
    price: 249.99,
    category: "earbuds",
    brand: "Apple",
    rating: 4.8,
    image: "/apple-airpods-pro-earbuds.jpg",
    description: "Wireless earbuds with active noise cancellation and spatial audio",
    specs: ["Active noise cancellation", "Adaptive audio", "USB-C charging"],
  },
  {
    id: 7,
    name: "Samsung Galaxy Buds2",
    price: 149.99,
    category: "earbuds",
    brand: "Samsung",
    rating: 4.6,
    image: "/samsung-galaxy-buds2-earbuds.jpg",
    description: "Budget-friendly earbuds with great sound and noise cancellation",
    specs: ["5 hour battery", "IPX7 water resistant", "Ambient mode"],
  },
  {
    id: 8,
    name: "Canon EOS R5",
    price: 3899.99,
    category: "cameras",
    brand: "Canon",
    rating: 4.9,
    image: "/canon-eos-r5-mirrorless-camera.jpg",
    description: "Professional mirrorless camera for photography and videography",
    specs: ["45MP sensor", "8K video", "RF mount"],
  },
  {
    id: 9,
    name: "GoPro Hero 12",
    price: 499.99,
    category: "cameras",
    brand: "GoPro",
    rating: 4.7,
    image: "/gopro-hero-12-action-camera.jpg",
    description: "Rugged action camera perfect for adventure and sports",
    specs: ["5.3K video", "Waterproof design", "HyperSmooth stabilization"],
  },
  {
    id: 10,
    name: "iPad Pro 12.9",
    price: 1199.99,
    category: "tablets",
    brand: "Apple",
    rating: 4.8,
    image: "/ipad-pro-12-9-tablet.jpg",
    description: "Powerful tablet with M2 chip and stunning Liquid Retina display",
    specs: ["8GB RAM", "256GB storage", "12.9 inch display"],
  },
  {
    id: 11,
    name: "Samsung Galaxy Tab S9",
    price: 799.99,
    category: "tablets",
    brand: "Samsung",
    rating: 4.6,
    image: "/samsung-galaxy-tab-s9-tablet.jpg",
    description: "Premium Android tablet with S Pen and vibrant display",
    specs: ["8GB RAM", "128GB storage", "11 inch AMOLED display"],
  },
  {
    id: 12,
    name: "Apple Watch Ultra 2",
    price: 799.99,
    category: "wearables",
    brand: "Apple",
    rating: 4.8,
    image: "/apple-watch-ultra-2-smartwatch.jpg",
    description: "Rugged smartwatch with advanced health monitoring",
    specs: ["Always-on display", "Water resistant", "ECG app"],
  },
  {
    id: 13,
    name: "Samsung Galaxy Watch6",
    price: 299.99,
    category: "wearables",
    brand: "Samsung",
    rating: 4.5,
    image: "/samsung-galaxy-watch6-smartwatch.jpg",
    description: "Feature-rich smartwatch with rotating bezel",
    specs: ["AMOLED display", "40mm case", "Sleep tracking"],
  },
  {
    id: 14,
    name: "DJI Air 3S",
    price: 999.99,
    category: "drones",
    brand: "DJI",
    rating: 4.9,
    image: "/dji-air-3s-drone-quadcopter.jpg",
    description: "Professional drone with advanced camera system",
    specs: ["4K camera", "46 min flight time", "Obstacle avoidance"],
  },
  {
    id: 15,
    name: "PlayStation 5",
    price: 499.99,
    category: "gaming",
    brand: "Sony",
    rating: 4.8,
    image: "/playstation-5-gaming-console.jpg",
    description: "Next-gen gaming console with blazing-fast SSD",
    specs: ["1TB storage", "4K gaming", "Included controller"],
  },
  {
    id: 16,
    name: "Xbox Series X",
    price: 499.99,
    category: "gaming",
    brand: "Microsoft",
    rating: 4.7,
    image: "/xbox-series-x-console.png",
    description: "Powerful gaming console with Game Pass access",
    specs: ["1TB storage", "4K gaming", "Backward compatible"],
  },
  {
    id: 17,
    name: "Corsair K95 Platinum Mechanical Keyboard",
    price: 229.99,
    category: "gaming",
    brand: "Corsair",
    rating: 4.6,
    image: "/corsair-k95-platinum-gaming-keyboard.jpg",
    description: "Premium mechanical gaming keyboard with RGB lighting",
    specs: ["Mechanical switches", "RGB lighting", "Programmable keys"],
  },
  {
    id: 18,
    name: "Samsung 27 inch 4K Monitor",
    price: 399.99,
    category: "monitors",
    brand: "Samsung",
    rating: 4.7,
    image: "/samsung-27-inch-4k-monitor.jpg",
    description: "Stunning 4K monitor for professional work and gaming",
    specs: ["4K resolution", "60Hz refresh", "USB-C connectivity"],
  },
  {
    id: 19,
    name: "LG OLED TV 55 inch",
    price: 1499.99,
    category: "televisions",
    brand: "LG",
    rating: 4.9,
    image: "/lg-oled-tv-55-inch-television.jpg",
    description: "Premium OLED TV with perfect blacks and vibrant colors",
    specs: ["4K resolution", "120Hz refresh", "Smart TV features"],
  },
  {
    id: 20,
    name: "Sony A90K OLED TV 65 inch",
    price: 2499.99,
    category: "televisions",
    brand: "Sony",
    rating: 5,
    image: "/sony-a90k-oled-tv-65-inch.jpg",
    description: "Flagship OLED TV with exceptional picture quality",
    specs: ["4K resolution", "120Hz refresh", "Cognitive processor"],
  },
  {
    id: 21,
    name: "Sonos Arc Soundbar",
    price: 799.99,
    category: "audio",
    brand: "Sonos",
    rating: 4.8,
    image: "/placeholder.svg?height=300&width=300",
    description: "Premium soundbar with Dolby Atmos support",
    specs: ["Dolby Atmos", "WiFi streaming", "HDMI eARC"],
  },
  {
    id: 22,
    name: "Beats Studio Pro Headphones",
    price: 399.99,
    category: "headphones",
    brand: "Beats",
    rating: 4.5,
    image: "/placeholder.svg?height=300&width=300",
    description: "Stylish headphones with premium sound and ANC",
    specs: ["Active noise cancellation", "40 hour battery", "Bluetooth 5.3"],
  },
  {
    id: 23,
    name: "Google Pixel 8 Pro",
    price: 899.99,
    category: "phones",
    brand: "Google",
    rating: 4.7,
    image: "/placeholder.svg?height=300&width=300",
    description: "AI-powered smartphone with exceptional computational photography",
    specs: ["6.7 inch display", "256GB storage", "Tensor G3 chip"],
  },
  {
    id: 24,
    name: "Lenovo ThinkPad X1",
    price: 1299.99,
    category: "laptops",
    brand: "Lenovo",
    rating: 4.6,
    image: "/placeholder.svg?height=300&width=300",
    description: "Business laptop with excellent keyboard and durability",
    specs: ["16GB RAM", "512GB SSD", "14 inch display"],
  },
  {
    id: 25,
    name: "Meta Quest 3",
    price: 499.99,
    category: "wearables",
    brand: "Meta",
    rating: 4.5,
    image: "/placeholder.svg?height=300&width=300",
    description: "Mixed reality headset for gaming and productivity",
    specs: ["4K pass-through", "128GB storage", "Touch controllers"],
  },
]
