export const products = [
  {
    id: 1,
    name: "Silk Blend Blazer",
    price: 289.0,
    category: "outerwear",
    image: "/elegant-silk-blazer-fashion-photography.jpg",
    description: "Luxurious silk blend blazer with contemporary tailoring.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Cream"],
    featured: true,
  },
  {
    id: 2,
    name: "Cashmere Sweater",
    price: 195.0,
    category: "tops",
    image: "/luxury-cashmere-sweater-neutral-tones.jpg",
    description: "Soft cashmere sweater in a relaxed fit.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Oatmeal", "Charcoal", "Burgundy"],
    featured: true,
  },
  {
    id: 3,
    name: "Tailored Wool Trousers",
    price: 165.0,
    category: "bottoms",
    image: "/tailored-wool-trousers-elegant.jpg",
    description: "Classic tailored trousers in premium wool.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Charcoal", "Camel"],
    featured: true,
  },
  {
    id: 4,
    name: "Linen Summer Dress",
    price: 225.0,
    category: "dresses",
    image: "/elegant-linen-dress-summer-fashion.jpg",
    description: "Breathable linen dress perfect for warm days.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Sand", "Sage"],
    featured: true,
  },
  {
    id: 5,
    name: "Leather Tote Bag",
    price: 345.0,
    category: "accessories",
    image: "/luxury-leather-tote-bag-minimalist.jpg",
    description: "Handcrafted leather tote with premium finish.",
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Cognac"],
    featured: true,
  },
  {
    id: 6,
    name: "Cotton Poplin Shirt",
    price: 125.0,
    category: "tops",
    image: "/crisp-cotton-shirt-fashion-photography.jpg",
    description: "Crisp cotton shirt with refined details.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Light Blue", "Pink"],
    featured: false,
  },
  {
    id: 7,
    name: "Wool Coat",
    price: 425.0,
    category: "outerwear",
    image: "/elegant-wool-coat-winter-fashion.jpg",
    description: "Timeless wool coat with modern silhouette.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Camel", "Grey"],
    featured: true,
  },
  {
    id: 8,
    name: "Silk Scarf",
    price: 95.0,
    category: "accessories",
    image: "/luxury-silk-scarf-pattern-elegant.jpg",
    description: "Elegant silk scarf with artisan print.",
    sizes: ["One Size"],
    colors: ["Multi", "Burgundy", "Navy"],
    featured: false,
  },
  {
    id: 9,
    name: "Pleated Midi Skirt",
    price: 145.0,
    category: "bottoms",
    image: "/pleated-midi-skirt-elegant-fashion.jpg",
    description: "Flowing pleated skirt in versatile length.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Cream"],
    featured: false,
  },
  {
    id: 10,
    name: "Merino Cardigan",
    price: 175.0,
    category: "tops",
    image: "/merino-wool-cardigan-cozy-elegant.jpg",
    description: "Lightweight merino cardigan for layering.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Cream", "Grey", "Black"],
    featured: false,
  },
  {
    id: 11,
    name: "Leather Belt",
    price: 85.0,
    category: "accessories",
    image: "/premium-leather-belt-minimalist.jpg",
    description: "Classic leather belt with signature buckle.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown", "Tan"],
    featured: false,
  },
  {
    id: 12,
    name: "Evening Gown",
    price: 495.0,
    category: "dresses",
    image: "/elegant-evening-gown-luxury-fashion.jpg",
    description: "Stunning evening gown for special occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Burgundy", "Emerald"],
    featured: true,
  },
]

export const categories = [
  { id: "all", name: "All Products" },
  { id: "tops", name: "Tops" },
  { id: "bottoms", name: "Bottoms" },
  { id: "dresses", name: "Dresses" },
  { id: "outerwear", name: "Outerwear" },
  { id: "accessories", name: "Accessories" },
]
